// Two Leaves and a Bud Master Product Database
const PRODUCTS = [
  {
    id: 1,
    title: "Organic Earl Grey",
    subtitle: "Bold Citrus Whole Leaf Black Tea",
    price: 9.99,
    img: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=500&auto=format&fit=crop&q=80",
    type: "black",
    format: "sachet",
    organic: true,
    caffeine: "high",
    tastingNotes: ["Citrusy", "Bergamot", "Full-Bodied"],
    ingredients: "Organic Black Tea, Organic Bergamot Oil",
    steepTemp: "208°F (97°C)",
    steepTime: 300, // 5 minutes
    featured: true,
    description: "A remarkably rich black tea combined with premium organic bergamot oil. Unlike standard Earl Greys, our whole leaf Assam base stands up to the citrus flavor for a perfectly balanced cup."
  },
  {
    id: 2,
    title: "Organic Assam",
    subtitle: "Rich & Malty Single Origin Black Tea",
    price: 9.99,
    img: "https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?w=500&auto=format&fit=crop&q=80",
    type: "black",
    format: "sachet",
    organic: true,
    caffeine: "high",
    tastingNotes: ["Malty", "Sweet", "Robust"],
    ingredients: "Organic Assam Black Tea",
    steepTemp: "208°F (97°C)",
    steepTime: 240, // 4 minutes
    featured: false,
    description: "Sourced from the finest organic gardens of Assam, India. This whole leaf black tea delivers a rich, malty infusion with a clean finish. Perfect with a splash of milk."
  },
  {
    id: 3,
    title: "Organic Peppermint",
    subtitle: "Crisp & Refreshing Caffeine-Free Herb Tea",
    price: 8.99,
    img: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80",
    type: "herbal",
    format: "sachet",
    organic: true,
    caffeine: "none",
    tastingNotes: ["Crisp", "Minty", "Cooling"],
    ingredients: "Organic Peppermint Leaves",
    steepTemp: "208°F (97°C)",
    steepTime: 300, // 5 minutes
    featured: true,
    description: "Made exclusively from premium organic peppermint leaves harvested at the peak of flavor. Refreshingly crisp, cooling, and naturally caffeine-free. An excellent digestif after dinner."
  },
  {
    id: 4,
    title: "Organic Chamomile",
    subtitle: "Soothing & Honey-like Herbal Infusion",
    price: 8.99,
    img: "https://images.unsplash.com/photo-1596162124707-4299b8288599?w=500&auto=format&fit=crop&q=80",
    type: "herbal",
    format: "sachet",
    organic: true,
    caffeine: "none",
    tastingNotes: ["Floral", "Honey-like", "Calming"],
    ingredients: "Organic Chamomile Flowers",
    steepTemp: "208°F (97°C)",
    steepTime: 300, // 5 minutes
    featured: true,
    description: "Whole chamomile flowers deliver a sweet, honey-like cup with calming properties. Sourced from pristine organic farms, our chamomile is clean, comforting, and perfect for bedtime."
  },
  {
    id: 5,
    title: "Jasmine Petal Green",
    subtitle: "Delicate & Fragrant Green Tea",
    price: 9.99,
    img: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=500&auto=format&fit=crop&q=80",
    type: "green",
    format: "sachet",
    organic: false,
    caffeine: "medium",
    tastingNotes: ["Floral", "Delicate", "Sweet"],
    ingredients: "Whole Green Tea Leaves, Jasmine Flowers",
    steepTemp: "175°F (80°C)",
    steepTime: 180, // 3 minutes
    featured: true,
    description: "Premium green tea leaves scented naturally with fresh jasmine blossoms. This tea offers a floral fragrance, a sweet taste, and a bright yellow cup without any grassy bitterness."
  },
  {
    id: 6,
    title: "Alpine Berry Iced Tea",
    subtitle: "Tart & Fruity Hibiscus Blend",
    price: 11.99,
    img: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500&auto=format&fit=crop&q=80",
    type: "herbal",
    format: "loose",
    organic: true,
    caffeine: "none",
    tastingNotes: ["Tart", "Fruity", "Berry-like"],
    ingredients: "Organic Hibiscus, Organic Rosehips, Organic Orange Peel, Organic Apple Pieces, Natural Berry Flavors",
    steepTemp: "208°F (97°C)",
    steepTime: 360, // 6 minutes
    featured: false,
    description: "A rich, ruby-red herbal infusion packed with tart hibiscus, rosehips, and sweet orange peel. Formulated specifically to make the ultimate refreshing iced tea for summer days."
  },
  {
    id: 7,
    title: "Ceremonial Grade Matcha",
    subtitle: "100% Pure Japanese Stone-Ground Matcha",
    price: 24.99,
    img: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=500&auto=format&fit=crop&q=80",
    type: "matcha",
    format: "powder",
    organic: true,
    caffeine: "high",
    tastingNotes: ["Umami", "Creamy", "Sweet Grass"],
    ingredients: "100% Organic Japanese Green Tea Powder",
    steepTemp: "160°F (70°C)",
    steepTime: 60, // 1 minute (whisking time)
    featured: true,
    description: "Stone-ground from shade-grown organic tencha leaves in Uji, Japan. Vibrant green color, creamy mouthfeel, and a rich umami flavor profile. Elevates your morning ritual."
  },
  {
    id: 8,
    title: "Organic Spiced Chai Latte Mix",
    subtitle: "Warming Sweet & Spiced Milk Soluble Mix",
    price: 13.99,
    img: "https://images.unsplash.com/photo-1578885136359-16c8bd4d3a8e?w=500&auto=format&fit=crop&q=80",
    type: "latte",
    format: "powder",
    organic: true,
    caffeine: "medium",
    tastingNotes: ["Spicy", "Cinnamon", "Sweet Cream"],
    ingredients: "Organic Cane Sugar, Organic Black Tea Powder, Organic Cinnamon, Organic Ginger, Organic Cardamom, Organic Cloves",
    steepTemp: "180°F (82°C)",
    steepTime: 120, // 2 minutes (stirring/dissolving)
    featured: false,
    description: "Create cafe-style chai lattes at home. A sweet and spicy soluble blend of organic black tea extract and fresh stone-ground spices. Just stir into hot milk or dairy-free alternative."
  },
  {
    id: 9,
    title: "Organic Turmeric Ginger",
    subtitle: "Warming & Spicy Functional Herb Tea",
    price: 9.99,
    img: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500&auto=format&fit=crop&q=80",
    type: "herbal",
    format: "sachet",
    organic: true,
    caffeine: "none",
    tastingNotes: ["Spicy", "Earthy", "Warming"],
    ingredients: "Organic Turmeric, Organic Ginger, Organic Licorice Root, Organic Orange Peel",
    steepTemp: "208°F (97°C)",
    steepTime: 360, // 6 minutes
    featured: false,
    description: "A powerful, warming blend of turmeric and ginger, offset with sweet licorice root and aromatic orange peel. Formulated to promote wellness and comfort in every sip."
  },
  {
    id: 10,
    title: "Loose Leaf Teaware Starter Set",
    subtitle: "Glass Teapot & Double-Wall Tea Mug",
    price: 29.99,
    img: "https://images.unsplash.com/photo-1582793988951-9aed5509eb97?w=500&auto=format&fit=crop&q=80",
    type: "teaware",
    format: "gear",
    organic: false,
    caffeine: "none",
    tastingNotes: ["N/A"],
    ingredients: "Borosilicate Glass, Stainless Steel Infuser Basket",
    steepTemp: "N/A",
    steepTime: 0,
    featured: false,
    description: "The ultimate set for brewing whole leaf teas. Features a 500ml heat-resistant borosilicate glass teapot with a removable fine mesh infuser, and a matching double-wall glass mug."
  }
];
