// ============================================================
// KalaKasturi — Master Product Database
// ============================================================
const products = [
  {
    id: 1,
    name: "Saraswati Inspired Painting",
    subtitle: "Original Indian Veena Woman Art",
    priceINR: 55540,
    priceUSD: 665,
    image: "https://i.etsystatic.com/65665644/r/il/0383f5/8000393884/il_340x270.8000393884_eymq.jpg",
    collection: "Spiritual",
    type: "Original Oil on Canvas",
    format: "original",
    featured: true,
    medium: "Oil on Canvas",
    size: "30×40 inches",
    year: "2024",
    tags: ["Spiritual", "Classical", "Devotional", "Goddess"],
    description: "An evocative and highly detailed original painting inspired by Goddess Saraswati — the Hindu deity of wisdom, music and arts — blending traditional Indian aesthetics with contemporary spiritual decor elements. This masterpiece celebrates the divine feminine and the power of music, making it a truly transformative centrepiece for any collector's home or sacred space."
  },
  {
    id: 2,
    name: "The Veena Lady Fine Art Print",
    subtitle: "Large 24×30 Vertical Oil Reproduction",
    priceINR: 9999,
    priceUSD: 120,
    image: "https://i.etsystatic.com/65665644/c/694/694/41/185/il/67741e/8000369780/il_340x270.8000369780_2mwx.jpg",
    collection: "Spiritual",
    type: "Fine Art Print",
    format: "print",
    featured: false,
    medium: "Archival Giclée Print",
    size: "24×30 inches",
    year: "2024",
    tags: ["Elegant", "Timeless", "Classical", "Print"],
    description: "A stunning, high-fidelity fine art print reproducing the magnificent 'Veena Lady' oil painting. Sized at a large 24×30 inches to serve as the perfect centrepiece for a living space, meditation room, or art collection. Printed on premium enhanced matte paper with archival inks that resist fading for over 100 years."
  },
  {
    id: 3,
    name: "Indian Woman with Fruit",
    subtitle: "Raja Ravi Varma Style Original Oil Painting",
    priceINR: 39949,
    priceUSD: 480,
    image: "https://i.etsystatic.com/65665644/r/il/7917c2/8051178813/il_340x270.8051178813_oxzh.jpg",
    collection: "Spiritual",
    type: "Original Oil on Canvas",
    format: "original",
    featured: true,
    medium: "Oil on Canvas",
    size: "24×30 inches",
    year: "2024",
    tags: ["Graceful", "Regal", "Warm", "Classical"],
    description: "Original oil painting capturing the timeless elegance of an Indian woman holding fruit, deeply inspired by the legendary Raja Ravi Varma style. The rich ochre tones and soft diffused light breathe life into the subject, while the intricate sari details reflect Ankita's mastery of classical Indian aesthetics. A one-of-a-kind heirloom piece."
  },
  {
    id: 4,
    name: "Leopard — Wildlife Painting",
    subtitle: "Original Oil on Canvas, 36×24 Unframed",
    priceINR: 81200,
    priceUSD: 975,
    image: "https://i.etsystatic.com/65665644/c/736/736/0/3/il/59ccc3/8058426003/il_340x270.8058426003_b4ma.jpg",
    collection: "Wildlife",
    type: "Original Oil on Canvas",
    format: "original",
    featured: true,
    medium: "Oil on Canvas (Gallery-Wrapped)",
    size: "36×24 inches",
    year: "2023",
    tags: ["Bold", "Dramatic", "Naturalistic", "Wildlife"],
    description: "Command attention with this fiercely realistic, hand-painted original leopard oil painting. An immersive 36×24 wildlife masterpiece that brings the raw power and piercing gaze of the jungle into your home. Every rosette, whisker, and amber eye is rendered with painstaking realism over weeks of detailed brushwork. A statement piece for serious collectors."
  },
  {
    id: 5,
    name: "Ektara Girl",
    subtitle: "Indian Village Musician Original Oil on Canvas",
    priceINR: 45900,
    priceUSD: 550,
    image: "https://i.etsystatic.com/65665644/c/981/981/14/98/il/30469f/7997157050/il_340x270.7997157050_1p6o.jpg",
    collection: "Spiritual",
    type: "Original Oil on Canvas",
    format: "original",
    featured: true,
    medium: "Oil on Canvas",
    size: "24×30 inches",
    year: "2023",
    tags: ["Folk", "Soulful", "Rustic", "Music"],
    description: "A soulful depiction of an Indian village musician playing the Ektara — a single-stringed folk instrument. This original oil on canvas captures the essence of rural folk music, village life, and the meditative joy of making music in quiet solitude. The warm earthy palette and loose, expressive brushwork give this piece an almost living quality."
  },
  {
    id: 6,
    name: "Sage Vishvamitra",
    subtitle: "Original Indian Mythology Spiritual Oil Painting",
    priceINR: 49540,
    priceUSD: 595,
    image: "https://i.etsystatic.com/65665644/c/736/736/0/86/il/9c68af/8048401327/il_340x270.8048401327_14ly.jpg",
    collection: "Spiritual",
    type: "Original Oil on Canvas",
    format: "original",
    featured: false,
    medium: "Oil on Canvas",
    size: "30×30 inches",
    year: "2023",
    tags: ["Sacred", "Ancient", "Ethereal", "Mythology"],
    description: "An awe-inspiring original painting of the revered sage Vishvamitra from Indian mythology, executed in the classic Raja Ravi Varma style. The sage's intense gaze, flowing robes, and the luminous atmospheric backdrop create a deeply spiritual aura. A sacred work for those who appreciate the depth of Indian classical art and spiritual heritage."
  },
  {
    id: 7,
    name: "Vishwamitra Fine Art Print",
    subtitle: "Raja Ravi Varma Inspired, 24×24 Enhanced Matte",
    priceINR: 9999,
    priceUSD: 120,
    image: "https://i.etsystatic.com/65665644/c/736/736/0/130/il/81bf42/8000239478/il_340x270.8000239478_q4qn.jpg",
    collection: "Spiritual",
    type: "Fine Art Print",
    format: "print",
    featured: false,
    medium: "Archival Giclée Print",
    size: "24×24 inches",
    year: "2023",
    tags: ["Sacred", "Classical", "Collectible", "Print"],
    description: "A premium fine art print of the Vishwamitra original painting on high-quality 24×24 inch enhanced matte paper, perfect for framing. Archival inks ensure 100+ years of colour brilliance with no fading. An accessible way to own a piece of KalaKasturi's spiritual art collection."
  }
];
