// KalaKasturi â€” Real Product Data
// Primary: Etsy shop | Additional: Amazon India
const PRODUCTS = [
  // â”€â”€ ETSY PRIMARY LISTINGS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: 1,
    slug: "saraswati-veena-woman-art",
    title: "Saraswati Inspired Painting",
    subtitle: "Original Indian Veena Woman Art",
    price: 55540,
    priceUSD: 667,
    medium: "Acrylic on Canvas",
    size: "24 Ã— 18 inches",
    collection: "spiritual",
    collectionLabel: "Spiritual Art",
    source: "etsy",
    available: true,
    featured: true,
    badge: "Best Seller",
    rating: 5,
    reviews: 12,
    img: "C:/Users/dhava/.gemini/antigravity/brain/8065801e-3420-43b7-9ec3-c98135d0a321/saraswati_veena_painting_1778617608320.png",
    tags: ["spiritual","indian classical","figurative","saraswati","veena"],
    description: "A breathtaking original acrylic painting inspired by the divine Goddess Saraswati. An Indian classical woman playing the Veena is rendered in the spirit of the great Raja Ravi Varma â€” rich jewel-toned saree, intricate gold jewellery, and an ethereal atmospheric background. Every brushstroke carries Ankita's reverence for Indian classical tradition.",
    details: ["100% hand-painted original","Signed & dated by the artist","Certificate of Authenticity included","Stretched on premium gallery-wrap canvas (ready to hang)","Archival-quality acrylic pigments"],
    care: "Dust with a soft dry cloth. Keep away from direct sunlight and high humidity."
  },
  {
    id: 2,
    slug: "leopard-oil-painting",
    title: "Original Leopard Oil Painting",
    subtitle: "Realistic Wildlife Wall Art",
    price: 81200,
    priceUSD: 975,
    medium: "Oil on Stretched Canvas",
    size: "30 Ã— 24 inches",
    collection: "wildlife",
    collectionLabel: "Wildlife",
    source: "etsy",
    available: true,
    featured: true,
    badge: "One of a Kind",
    rating: 5,
    reviews: 8,
    img: "C:/Users/dhava/.gemini/antigravity/brain/8065801e-3420-43b7-9ec3-c98135d0a321/leopard_oil_painting_1778617627890.png",
    tags: ["wildlife","leopard","oil painting","realistic","nature"],
    description: "A masterful, photorealistic oil painting of a leopard that commands any room it enters. Ankita spent weeks layering transparent glazes of oil paint to achieve the luminous depth of the spotted coat and those arresting golden eyes. This is a statement piece for the discerning collector.",
    details: ["100% hand-painted original oil on canvas","Signed & dated by the artist","Certificate of Authenticity included","Gallery-wrapped, ready to hang","Uses professional-grade oil pigments that last generations"],
    care: "Lightly dust. Do not clean with water. Professional conservation recommended every 10â€“15 years."
  },
  {
    id: 3,
    slug: "veena-lady-fine-art-print",
    title: "The Veena Lady",
    subtitle: "Fine Art Giclee Print",
    price: 9999,
    priceUSD: 120,
    medium: "Giclee Fine Art Print",
    size: "16 Ã— 12 inches (multiple sizes available)",
    collection: "prints",
    collectionLabel: "Prints & Sketches",
    source: "etsy",
    available: true,
    featured: false,
    badge: "Affordable",
    rating: 4.9,
    reviews: 24,
    img: "C:/Users/dhava/.gemini/antigravity/brain/8065801e-3420-43b7-9ec3-c98135d0a321/veena_lady_print_1778617687881.png",
    tags: ["print","veena","classical","affordable","giclee"],
    description: "Bring the elegance of KalaKasturi's most beloved classical figure into your home at an accessible price point. This museum-quality giclee print is produced on 300gsm archival cotton rag paper using pigment inks that resist fading for over 100 years. Signed and numbered limited edition.",
    details: ["Limited edition of 50 â€” signed & numbered","Printed on 300gsm archival cotton rag paper","Pigment inks rated 100+ year lightfastness","Ships flat with foam-board backing","Unframed (framing guidance included)"],
    care: "Frame under UV-protective glass for best preservation."
  },
  {
    id: 4,
    slug: "indian-woman-fruit-raja-ravi-varma",
    title: "Indian Woman with Fruit",
    subtitle: "Raja Ravi Varma Style Original",
    price: 39949,
    priceUSD: 480,
    medium: "Oil on Canvas",
    size: "20 Ã— 16 inches",
    collection: "classical",
    collectionLabel: "Classical Figurative",
    source: "etsy",
    available: true,
    featured: true,
    badge: "Raja Ravi Varma Style",
    rating: 5,
    reviews: 6,
    img: "C:/Users/dhava/.gemini/antigravity/brain/8065801e-3420-43b7-9ec3-c98135d0a321/indian_woman_fruit_painting_1778617638192.png",
    tags: ["figurative","raja ravi varma","classical","indian woman","oil"],
    description: "Deeply rooted in the tradition of India's greatest painter Raja Ravi Varma, this original oil captures an Indian woman in traditional attire offering tropical fruits in a brass bowl. Warm ochre skin tones, lush tropical foliage, and the painter's signature attention to fabric texture make this a timeless heirloom.",
    details: ["100% original oil on canvas","Raja Ravi Varma inspired style","Signed by artist Ankita","Certificate of Authenticity","Gallery-wrapped, ready to hang"],
    care: "Avoid direct sunlight. Dust with soft dry cloth."
  },
  {
    id: 5,
    slug: "ektara-girl-village-musician",
    title: "Ektara Girl",
    subtitle: "Indian Village Musician Art",
    price: 45900,
    priceUSD: 551,
    medium: "Oil on Canvas",
    size: "24 Ã— 18 inches",
    collection: "classical",
    collectionLabel: "Classical Figurative",
    source: "etsy",
    available: true,
    featured: true,
    badge: "Collector's Pick",
    rating: 5,
    reviews: 9,
    img: "C:/Users/dhava/.gemini/antigravity/brain/8065801e-3420-43b7-9ec3-c98135d0a321/ektara_girl_painting_1778617658636.png",
    tags: ["figurative","folk","music","village","ektara","oil"],
    description: "A soulful portrayal of a village girl lost in the music of the Ektara â€” a single-stringed folk instrument of India. Painted with earthy, warm tones and expressive brushwork, this piece captures the timeless innocence of rural India. Ankita drew inspiration from her childhood memories near the foothills of the Himalayas.",
    details: ["100% original oil on canvas","Signed & dated by artist Ankita","Certificate of Authenticity","Gallery-wrapped, ready to hang","Painted in Rishikesh, Uttarakhand"],
    care: "Keep away from moisture and direct sunlight."
  },
  {
    id: 6,
    slug: "vishvamitra-mythology-painting",
    title: "Vishvamitra â€” The Sage King",
    subtitle: "Original Indian Mythology Art",
    price: 49540,
    priceUSD: 595,
    medium: "Oil on Canvas",
    size: "24 Ã— 30 inches",
    collection: "spiritual",
    collectionLabel: "Spiritual Art",
    source: "etsy",
    available: true,
    featured: false,
    badge: "Mythology Series",
    rating: 5,
    reviews: 5,
    img: "C:/Users/dhava/.gemini/antigravity/brain/8065801e-3420-43b7-9ec3-c98135d0a321/vishvamitra_mythology_painting_1778617673995.png",
    tags: ["spiritual","mythology","vishvamitra","sage","epic","oil"],
    description: "The legendary Sage-King Vishvamitra â€” warrior turned brahmarshi â€” brought to life in powerful oils. Celestial light breaks through stormy clouds as the sage stands in divine resolve. Part of Ankita's ongoing Indian Mythology Series, this piece honours the epic tradition of the Ramayana and Mahabharata.",
    details: ["Part of the Indian Mythology Series","100% original oil on canvas","Signed & dated by artist Ankita","Certificate of Authenticity","Gallery-wrapped, ready to hang"],
    care: "Display in low-humidity environment."
  },
  // â”€â”€ AMAZON ADDITIONAL LISTINGS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: 7,
    slug: "ancient-lady-oil-painting",
    title: "Ancient Lady",
    subtitle: "Original Oil Painting on Canvas",
    price: 8999,
    priceUSD: 108,
    medium: "Oil on Canvas",
    size: "12 Ã— 10 inches",
    collection: "classical",
    collectionLabel: "Classical Figurative",
    source: "amazon",
    available: true,
    featured: false,
    badge: "Entry Collection",
    rating: 4.7,
    reviews: 31,
    img: "C:/Users/dhava/.gemini/antigravity/brain/8065801e-3420-43b7-9ec3-c98135d0a321/ancient_lady_painting_1778617712253.png",
    tags: ["figurative","classical","portrait","ancient","oil"],
    description: "An exquisite small-format oil painting of an ancient Indian noblewoman. Perfect as a gift or for smaller spaces, this painting packs remarkable detail into a compact size â€” ornate jewellery, draped fabric and a gaze that speaks across centuries.",
    details: ["Original oil on canvas","Signed by artist","Certificate of Authenticity","Ready to hang"],
    care: "Dust with soft cloth. Avoid moisture."
  },
  {
    id: 8,
    slug: "feminine-energy-abstract",
    title: "Feminine Energy",
    subtitle: "Abstract Oil Painting",
    price: 18999,
    priceUSD: 228,
    medium: "Oil on Canvas",
    size: "18 Ã— 18 inches",
    collection: "abstract",
    collectionLabel: "Abstract",
    source: "amazon",
    available: true,
    featured: true,
    badge: "Abstract Series",
    rating: 4.8,
    reviews: 18,
    img: "C:/Users/dhava/.gemini/antigravity/brain/8065801e-3420-43b7-9ec3-c98135d0a321/feminine_energy_abstract_1778617753185.png",
    tags: ["abstract","feminine","spiritual","contemporary","oil"],
    description: "Flowing forms of rose-gold and deep burgundy swirl in divine feminine energy. This abstract oil painting channels the concept of Shakti â€” the primordial creative force â€” through pure colour and movement. A conversation starter for any contemporary interior.",
    details: ["Original abstract oil on canvas","Contemporary Indian art style","Signed by artist Ankita","Certificate of Authenticity","Gallery-wrapped"],
    care: "Wipe gently with dry cloth."
  },
  {
    id: 9,
    slug: "cosmic-mirage-abstract",
    title: "Cosmic Mirage",
    subtitle: "Abstract Oil Painting",
    price: 15999,
    priceUSD: 192,
    medium: "Oil on Canvas",
    size: "16 Ã— 16 inches",
    collection: "abstract",
    collectionLabel: "Abstract",
    source: "amazon",
    available: true,
    featured: false,
    badge: "Abstract Series",
    rating: 4.6,
    reviews: 14,
    img: "C:/Users/dhava/.gemini/antigravity/brain/8065801e-3420-43b7-9ec3-c98135d0a321/cosmic_mirage_abstract_1778617727382.png",
    tags: ["abstract","cosmic","contemporary","purple","gold"],
    description: "Galaxies and nebulae swirl in rich purples, indigos, and gold â€” a meditation on the infinite cosmos. Painted with impasto technique for dramatic textural depth, Cosmic Mirage turns any wall into a window to the universe.",
    details: ["Original oil on canvas with impasto texture","Contemporary abstract style","Signed by artist","Certificate of Authenticity","Gallery-wrapped"],
    care: "Dust with soft dry cloth."
  },
  {
    id: 10,
    slug: "charlie-chaplin-charcoal",
    title: "Charlie Chaplin",
    subtitle: "Original Charcoal Drawing",
    price: 4999,
    priceUSD: 60,
    medium: "Charcoal on Paper",
    size: "14 Ã— 11 inches",
    collection: "prints",
    collectionLabel: "Prints & Sketches",
    source: "amazon",
    available: true,
    featured: false,
    badge: "Limited Sketch",
    rating: 4.9,
    reviews: 42,
    img: "C:/Users/dhava/.gemini/antigravity/brain/8065801e-3420-43b7-9ec3-c98135d0a321/charlie_chaplin_charcoal_1778617741949.png",
    tags: ["charcoal","portrait","charlie chaplin","sketch","affordable"],
    description: "Ankita's masterful charcoal hand captures the beloved Charlie Chaplin in dramatic chiaroscuro â€” the iconic bowler hat, the gentle mustache, and those soulful eyes that told a thousand stories without a single word. A timeless piece for lovers of cinema and fine art alike.",
    details: ["Original charcoal on acid-free paper","Signed by artist Ankita","Ships flat in protective sleeve","Archival framing recommended"],
    care: "Frame under glass immediately. Keep away from moisture."
  },
  {
    id: 11,
    slug: "shiv-shakti-print",
    title: "Shiv Shakti",
    subtitle: "Fine Art Print",
    price: 3999,
    priceUSD: 48,
    medium: "Giclee Fine Art Print",
    size: "12 Ã— 16 inches",
    collection: "spiritual",
    collectionLabel: "Spiritual Art",
    source: "amazon",
    available: true,
    featured: false,
    badge: "Spiritual Series",
    rating: 4.8,
    reviews: 67,
    img: "C:/Users/dhava/.gemini/antigravity/brain/8065801e-3420-43b7-9ec3-c98135d0a321/vishvamitra_mythology_painting_1778617673995.png",
    tags: ["spiritual","shiva","shakti","print","devotional"],
    description: "The divine union of Shiva and Shakti â€” consciousness and energy â€” rendered in vivid devotional colours. This premium giclee print makes an ideal housewarming or puja-room gift. Ships in protective packaging.",
    details: ["Limited edition giclee print","Archival pigment inks","Signed & numbered","Ships flat, ready to frame"],
    care: "Frame under UV-protective glass."
  },
  {
    id: 12,
    slug: "milkmaid-watercolour",
    title: "The Milkmaid",
    subtitle: "Original Watercolour Painting",
    price: 4999,
    priceUSD: 60,
    medium: "Watercolour on Paper",
    size: "10 Ã— 8 inches",
    collection: "classical",
    collectionLabel: "Classical Figurative",
    source: "amazon",
    available: true,
    featured: false,
    badge: "Watercolour",
    rating: 4.7,
    reviews: 22,
    img: "C:/Users/dhava/.gemini/antigravity/brain/8065801e-3420-43b7-9ec3-c98135d0a321/ancient_lady_painting_1778617712253.png",
    tags: ["watercolour","figurative","village","milkmaid","indian"],
    description: "A delicate watercolour study of a village milkmaid â€” soft washes of ochre and blue capture her quiet dignity. This intimate small-format work shows Ankita's versatility beyond oils, and is an ideal entry point into original art collecting.",
    details: ["Original watercolour on 300gsm cold-press paper","Signed by artist","Ships flat in protective sleeve"],
    care: "Frame under glass to prevent moisture damage."
  }
];

// Collections metadata
const COLLECTIONS = [
  { id: "all",      label: "All Works",          icon: "âœ¦" },
  { id: "spiritual",label: "Spiritual Art",       icon: "ðŸ•‰" },
  { id: "classical",label: "Classical Figurative", icon: "ðŸª·" },
  { id: "wildlife", label: "Wildlife",             icon: "ðŸ†" },
  { id: "abstract", label: "Abstract",             icon: "ðŸŒ€" },
  { id: "prints",   label: "Prints & Sketches",   icon: "ðŸ–‹" },
];

// Testimonials
const TESTIMONIALS = [
  {
    name: "Priya Sharma",
    location: "Mumbai",
    rating: 5,
    text: "The Saraswati painting arrived perfectly packed and it's even more stunning in person. Ankita's brushwork has such soul â€” you can feel the devotion in every stroke. My living room is transformed.",
    artwork: "Saraswati Inspired Painting"
  },
  {
    name: "Rahul Mehta",
    location: "Bangalore",
    rating: 5,
    text: "I ordered the Leopard painting as a gift for my father and he was moved to tears. The detail in the eyes is extraordinary. Shipping was fast and the certificate of authenticity is a beautiful touch.",
    artwork: "Original Leopard Oil Painting"
  },
  {
    name: "Ananya Krishnan",
    location: "Chennai",
    rating: 5,
    text: "Bought the Ektara Girl for our office. Every colleague who walks in asks about it. KalaKasturi's customer service is wonderful â€” Ankita even sent a personal note about the painting's story.",
    artwork: "Ektara Girl Painting"
  },
  {
    name: "David Fernandez",
    location: "Goa",
    rating: 5,
    text: "Purchased three prints and an original. The quality is museum-level. I've bought from many galleries worldwide and this competes with the best at a fraction of the price.",
    artwork: "Multiple Artworks"
  }
];
